trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@1
  inputs:
    containerRegistry: 'docker-hub-rezarahman'
    repository: 'rezarahman/azure-cafe'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'v1'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-cluster-reza'
    command: 'delete'
    useConfigurationFile: true
    configuration: 'azure-cafe.yml'
- task: Kubernetes@2
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-cluster-reza'
    command: 'create'
    useConfigurationFile: true
    configuration: 'azure-cafe.yml'