trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-rezarahman'
    repository: 'rezarahman/azure-cafe'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'v1'
- task: Kubernetes@1
  continueOnError: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-cafe-cluster'
    command: 'delete'
    useConfigurationFile: true
    configuration: 'azure-cafe.yml'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-cafe-cluster'
    command: 'create'
    useConfigurationFile: true
    configuration: 'azure-cafe.yml'
    forceUpdateConfigMap: true
    configMapName: 'application-insights-key'
    configMapArguments: '--from-literal=APPLICATION_INSIGHTS_KEY=7b34041f-3ba4-4b88-b05a-ffeb955a19aa'
